export interface Product {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviews: number;
  image: string;
  category: string;
  description: string;
  inStock: boolean;
  badge?: string;
}

export const products: Product[] = [
  {
    id: "1",
    name: "Wireless Bluetooth Headphones",
    price: 2999,
    originalPrice: 4999,
    rating: 4.5,
    reviews: 1247,
    image: "/products/headphones.jpg",
    category: "Electronics",
    description: "Premium wireless headphones with active noise cancellation, 40-hour battery life, and crystal-clear audio quality. Perfect for music lovers and professionals.",
    inStock: true,
    badge: "Bestseller",
  },
  {
    id: "2",
    name: "Smart Fitness Band",
    price: 1799,
    originalPrice: 2499,
    rating: 4.3,
    reviews: 892,
    image: "/products/fitness-band.jpg",
    category: "Electronics",
    description: "Track your health with precision. Features heart rate monitoring, sleep tracking, SpO2 sensor, and 14-day battery life.",
    inStock: true,
    badge: "AI Pick",
  },
  {
    id: "3",
    name: "Gaming Mouse",
    price: 1299,
    originalPrice: 1999,
    rating: 4.7,
    reviews: 2341,
    image: "/products/gaming-mouse.jpg",
    category: "Electronics",
    description: "RGB gaming mouse with 16000 DPI sensor, programmable buttons, and ergonomic design for extended gaming sessions.",
    inStock: true,
  },
  {
    id: "4",
    name: "Running Shoes",
    price: 3499,
    originalPrice: 5999,
    rating: 4.6,
    reviews: 567,
    image: "/products/running-shoes.jpg",
    category: "Sports & Fitness",
    description: "Lightweight running shoes with advanced cushioning technology, breathable mesh upper, and superior grip for all terrains.",
    inStock: true,
    badge: "Top Rated",
  },
  {
    id: "5",
    name: "Laptop Backpack",
    price: 1999,
    originalPrice: 2999,
    rating: 4.4,
    reviews: 1123,
    image: "/products/backpack.jpg",
    category: "Fashion",
    description: "Water-resistant laptop backpack with anti-theft design, USB charging port, and multiple compartments for organization.",
    inStock: true,
  },
  {
    id: "6",
    name: "Smart Watch Pro",
    price: 8999,
    originalPrice: 12999,
    rating: 4.8,
    reviews: 3456,
    image: "/products/smartwatch.jpg",
    category: "Electronics",
    description: "Premium smartwatch with AMOLED display, GPS, health monitoring, and seamless smartphone integration.",
    inStock: true,
    badge: "Premium",
  },
  // Electronics
  {
    id: "7",
    name: "Wireless Earbuds Pro",
    price: 4999,
    originalPrice: 6999,
    rating: 4.6,
    reviews: 2134,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop",
    category: "Electronics",
    description: "True wireless earbuds with spatial audio, adaptive EQ, and 30-hour total battery life with charging case.",
    inStock: true,
    badge: "New",
  },
  {
    id: "8",
    name: "4K Action Camera",
    price: 12999,
    originalPrice: 18999,
    rating: 4.5,
    reviews: 876,
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=400&h=400&fit=crop",
    category: "Electronics",
    description: "Waterproof 4K action camera with image stabilization, 170° wide-angle lens, and WiFi connectivity.",
    inStock: true,
  },
  {
    id: "9",
    name: "Mechanical Keyboard RGB",
    price: 3499,
    originalPrice: 4999,
    rating: 4.8,
    reviews: 1567,
    image: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=400&h=400&fit=crop",
    category: "Electronics",
    description: "Hot-swappable mechanical keyboard with RGB backlighting, PBT keycaps, and customizable macros.",
    inStock: true,
    badge: "Top Rated",
  },
  {
    id: "10",
    name: "Portable Power Bank 20000mAh",
    price: 1499,
    originalPrice: 2299,
    rating: 4.4,
    reviews: 3421,
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop",
    category: "Electronics",
    description: "Fast-charging power bank with dual USB-C ports, LED display, and airplane-safe design.",
    inStock: true,
  },
  {
    id: "11",
    name: "Smart Home Speaker",
    price: 5999,
    originalPrice: 7999,
    rating: 4.3,
    reviews: 1234,
    image: "https://images.unsplash.com/photo-1543512214-318c7553f230?w=400&h=400&fit=crop",
    category: "Electronics",
    description: "Voice-controlled smart speaker with premium sound, built-in AI assistant, and smart home integration.",
    inStock: true,
    badge: "AI Pick",
  },
  // Fashion
  {
    id: "12",
    name: "Leather Wallet Premium",
    price: 1299,
    originalPrice: 1999,
    rating: 4.5,
    reviews: 892,
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400&h=400&fit=crop",
    category: "Fashion",
    description: "Genuine leather wallet with RFID blocking, multiple card slots, and elegant minimalist design.",
    inStock: true,
  },
  {
    id: "13",
    name: "Aviator Sunglasses",
    price: 2499,
    originalPrice: 3999,
    rating: 4.6,
    reviews: 567,
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop",
    category: "Fashion",
    description: "Classic aviator sunglasses with polarized lenses, UV400 protection, and lightweight metal frame.",
    inStock: true,
    badge: "Trending",
  },
  {
    id: "14",
    name: "Canvas Tote Bag",
    price: 899,
    originalPrice: 1499,
    rating: 4.3,
    reviews: 1234,
    image: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=400&h=400&fit=crop",
    category: "Fashion",
    description: "Eco-friendly canvas tote bag with reinforced handles, inner pockets, and stylish minimalist print.",
    inStock: true,
  },
  {
    id: "15",
    name: "Formal Dress Watch",
    price: 4999,
    originalPrice: 7999,
    rating: 4.7,
    reviews: 445,
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=400&fit=crop",
    category: "Fashion",
    description: "Elegant stainless steel dress watch with sapphire crystal, Japanese movement, and leather strap.",
    inStock: true,
    badge: "Premium",
  },
  // Home & Kitchen
  {
    id: "16",
    name: "Air Fryer 5.5L",
    price: 4999,
    originalPrice: 7999,
    rating: 4.6,
    reviews: 2345,
    image: "https://images.unsplash.com/photo-1648136219192-5c23de6ba9f1?w=400&h=400&fit=crop",
    category: "Home & Kitchen",
    description: "Digital air fryer with 8 preset cooking modes, rapid air technology, and easy-clean basket.",
    inStock: true,
    badge: "Bestseller",
  },
  {
    id: "17",
    name: "Robot Vacuum Cleaner",
    price: 15999,
    originalPrice: 24999,
    rating: 4.4,
    reviews: 987,
    image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=400&h=400&fit=crop",
    category: "Home & Kitchen",
    description: "Smart robot vacuum with LiDAR navigation, app control, 180-min runtime, and automatic dust disposal.",
    inStock: true,
    badge: "AI Pick",
  },
  {
    id: "18",
    name: "Instant Pot Multi-Cooker",
    price: 6999,
    originalPrice: 9999,
    rating: 4.7,
    reviews: 1876,
    image: "https://images.unsplash.com/photo-1585664811087-47f65abbad64?w=400&h=400&fit=crop",
    category: "Home & Kitchen",
    description: "7-in-1 multi-cooker with pressure cook, slow cook, rice cooker, steamer, and yogurt maker functions.",
    inStock: true,
  },
  {
    id: "19",
    name: "Smart LED Desk Lamp",
    price: 1999,
    originalPrice: 2999,
    rating: 4.5,
    reviews: 678,
    image: "https://images.unsplash.com/photo-1534073737927-85f1ebff1f5d?w=400&h=400&fit=crop",
    category: "Home & Kitchen",
    description: "Touch-controlled desk lamp with adjustable brightness, color temperature, and USB charging port.",
    inStock: true,
  },
  {
    id: "20",
    name: "Premium Coffee Maker",
    price: 8999,
    originalPrice: 12999,
    rating: 4.8,
    reviews: 543,
    image: "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=400&h=400&fit=crop",
    category: "Home & Kitchen",
    description: "Bean-to-cup coffee maker with built-in grinder, milk frother, and customizable brewing strength.",
    inStock: true,
    badge: "Top Rated",
  },
  // Sports & Fitness
  {
    id: "21",
    name: "Yoga Mat Premium",
    price: 1499,
    originalPrice: 2499,
    rating: 4.5,
    reviews: 1234,
    image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=400&fit=crop",
    category: "Sports & Fitness",
    description: "Extra-thick yoga mat with alignment lines, non-slip surface, and eco-friendly TPE material.",
    inStock: true,
  },
  {
    id: "22",
    name: "Adjustable Dumbbells Set",
    price: 9999,
    originalPrice: 14999,
    rating: 4.7,
    reviews: 567,
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=400&fit=crop",
    category: "Sports & Fitness",
    description: "Space-saving adjustable dumbbells from 2.5kg to 25kg with quick-change weight system.",
    inStock: true,
    badge: "New",
  },
  {
    id: "23",
    name: "Wireless Sports Earphones",
    price: 2999,
    originalPrice: 4999,
    rating: 4.4,
    reviews: 890,
    image: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=400&h=400&fit=crop",
    category: "Sports & Fitness",
    description: "Sweat-resistant wireless earphones with secure ear hooks, deep bass, and 12-hour battery life.",
    inStock: true,
  },
  {
    id: "24",
    name: "Resistance Bands Set",
    price: 799,
    originalPrice: 1299,
    rating: 4.3,
    reviews: 2345,
    image: "https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=400&h=400&fit=crop",
    category: "Sports & Fitness",
    description: "5-level resistance bands with carrying bag, door anchor, and exercise guide for full-body workout.",
    inStock: true,
  },
  {
    id: "25",
    name: "Smart Jump Rope",
    price: 1999,
    originalPrice: 2999,
    rating: 4.6,
    reviews: 456,
    image: "https://images.unsplash.com/photo-1434682881908-b43d0467b798?w=400&h=400&fit=crop",
    category: "Sports & Fitness",
    description: "Digital jump rope with calorie counter, jump counter, app connectivity, and adjustable length.",
    inStock: true,
    badge: "AI Pick",
  },
  // Books
  {
    id: "26",
    name: "The Art of Thinking Clearly",
    price: 399,
    originalPrice: 599,
    rating: 4.6,
    reviews: 3456,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop",
    category: "Books",
    description: "Bestselling guide to cognitive biases and logical fallacies for better decision-making.",
    inStock: true,
    badge: "Bestseller",
  },
  {
    id: "27",
    name: "Atomic Habits",
    price: 499,
    originalPrice: 799,
    rating: 4.9,
    reviews: 8765,
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=400&fit=crop",
    category: "Books",
    description: "Proven framework for building good habits and breaking bad ones by James Clear.",
    inStock: true,
    badge: "Top Rated",
  },
  {
    id: "28",
    name: "The Psychology of Money",
    price: 449,
    originalPrice: 699,
    rating: 4.7,
    reviews: 5432,
    image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&h=400&fit=crop",
    category: "Books",
    description: "Timeless lessons on wealth, greed, and happiness by Morgan Housel.",
    inStock: true,
  },
  {
    id: "29",
    name: "Deep Work",
    price: 399,
    originalPrice: 599,
    rating: 4.5,
    reviews: 2345,
    image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400&h=400&fit=crop",
    category: "Books",
    description: "Rules for focused success in a distracted world by Cal Newport.",
    inStock: true,
  },
  {
    id: "30",
    name: "Thinking, Fast and Slow",
    price: 549,
    originalPrice: 899,
    rating: 4.6,
    reviews: 4567,
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=400&fit=crop",
    category: "Books",
    description: "Nobel laureate Daniel Kahneman's groundbreaking exploration of how we think.",
    inStock: true,
    badge: "Premium",
  },
];

export const categories = [
  { id: "electronics", name: "Electronics", icon: "Smartphone", count: 1250 },
  { id: "fashion", name: "Fashion", icon: "Shirt", count: 3420 },
  { id: "home-kitchen", name: "Home & Kitchen", icon: "Home", count: 2180 },
  { id: "sports-fitness", name: "Sports & Fitness", icon: "Dumbbell", count: 890 },
  { id: "books", name: "Books", icon: "BookOpen", count: 5670 },
];

export const formatPrice = (price: number): string => {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    minimumFractionDigits: 0,
  }).format(price);
};
